name: Vulnerability Scan Schedule

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2AM UTC
  workflow_dispatch:      # Manual trigger
  
- name: Scan with Docker
  run: |
    docker run --rm \
      -v $(pwd)/results:/results \
      projectdiscovery/nuclei:latest \
      -u https://example.com \
      -json -o /results/scan.json
