name: Vulnerability Scan Schedule

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2AM UTC
  workflow_dispatch:      # Manual trigger
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          # Cài đặt dependencies
          sudo apt update
          sudo apt install -y jq unzip
      
          # Tải Nuclei bản mới nhất từ GitHub Releases
          NUCLEI_VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r .tag_name)
          wget "https://github.com/projectdiscovery/nuclei/releases/download/${NUCLEI_VERSION}/nuclei_${NUCLEI_VERSION:1}_linux_amd64.zip"
    
          # Giải nén và cài đặt
          unzip nuclei_${NUCLEI_VERSION:1}_linux_amd64.zip
          chmod +x nuclei
          sudo mv nuclei /usr/local/bin/
    
          # Cài đặt templates
          nuclei -update-templates
    
          # Kiểm tra
          nuclei -version

      - name: Run Scan
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python scripts/scanner.py
