name: Vulnerability Scan Schedule

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2AM UTC
  workflow_dispatch:      # Manual trigger
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nuclei
         run: |
           sudo apt update
           sudo apt install -y jq unzip
    
           # Tải và cài đặt nuclei mà không cần giải nén README
           NUCLEI_VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r .tag_name)
           wget -q "https://github.com/projectdiscovery/nuclei/releases/download/${NUCLEI_VERSION}/nuclei_${NUCLEI_VERSION:1}_linux_amd64.zip" -O nuclei.zip
    
           # Chỉ giải nén file thực thi
           unzip -j nuclei.zip nuclei -d /tmp
           chmod +x /tmp/nuclei
           sudo mv /tmp/nuclei /usr/local/bin/
    
           # Cleanup
          rm nuclei.zip
    
           # Verify
           nuclei -version
      - name: Run Scan
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python scripts/scanner.py
