name: Vulnerability Scan Schedule

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2AM UTC
  workflow_dispatch:      # Manual trigger
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          # Cài đặt Nuclei và các công cụ cần thiết
          sudo apt update
          sudo apt install -y jq
          
          # Tải và cài đặt nuclei từ ProjectDiscovery
          curl -sL https://raw.githubusercontent.com/projectdiscovery/nuclei/v3/bin/install.sh | sh
          
          # Thêm vào PATH
          echo "$HOME/go/bin" >> $GITHUB_PATH
          
          # Cập nhật templates
          nuclei -update-templates
          
          # Kiểm tra phiên bản
          nuclei -version

      - name: Run Scan
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python scripts/scanner.py
